# Generated by Django 5.1 on 2024-08-17 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rol.rol', verbose_name='Rol'),
        ),
    ]
