# Generated by Django 5.1 on 2024-08-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Rol'},
        ),
    ]
