# Generated by Django 5.1 on 2024-08-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_alter_rol_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
